name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.issue;
            const labels = context.payload.pull_request?.labels || [];
            
            // Check if PR has auto-merge label
            if (labels.some(label => label.name === 'auto-merge')) {
              // Check if PR has required labels
              const requiredLabels = ['approved', 'ci-passed'];
              const hasRequiredLabels = requiredLabels.every(label =>
                labels.some(l => l.name === label)
              );
              
              if (hasRequiredLabels) {
                // Enable auto-merge
                github.rest.pulls.enableAutoMerge({
                  owner: issue.owner,
                  repo: issue.repo,
                  pull_number: issue.number,
                  merge_method: 'squash'
                });
              }
            } 